export type GameLogEntry = {
  time: string;
  quarter: string;
  team: string;
  player: string;
  play: string;
  distance: string;
  result: string;
  assist: string;
};

export const game1Log: GameLogEntry[] = [
  {
    time: "11:42",
    quarter: "Q1",
    team: "SAS",
    player: "Stephon Castle",
    play: "3PT Jump Shot",
    distance: "26'",
    result: "made",
    assist: "Dylan Harper",
  },
  {
    time: "11:17",
    quarter: "Q1",
    team: "OKC",
    player: "Isaiah Hartenstein",
    play: "Floating Jump Shot",
    distance: "9'",
    result: "miss",
    assist: "",
  },
  {
    time: "10:42",
    quarter: "Q1",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Running Jump Shot",
    distance: "26'",
    result: "miss",
    assist: "",
  },
  {
    time: "10:37",
    quarter: "Q1",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Tip Layup Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "10:36",
    quarter: "Q1",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Tip Layup Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "10:35",
    quarter: "Q1",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Tip Layup Shot",
    distance: "",
    result: "made",
    assist: "",
  },
  {
    time: "10:21",
    quarter: "Q1",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Pullup Jump Shot",
    distance: "7'",
    result: "miss",
    assist: "",
  },
  {
    time: "09:54",
    quarter: "Q1",
    team: "OKC",
    player: "Luguentz Dort",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "09:33",
    quarter: "Q1",
    team: "SAS",
    player: "Dylan Harper",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "09:08",
    quarter: "Q1",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "3PT Step Back Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "08:46",
    quarter: "Q1",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "08:27",
    quarter: "Q1",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Step Back Jump Shot",
    distance: "26'",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "08:09",
    quarter: "Q1",
    team: "SAS",
    player: "Dylan Harper",
    play: "3PT Running Jump Shot",
    distance: "27'",
    result: "miss",
    assist: "",
  },
  {
    time: "07:58",
    quarter: "Q1",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "07:47",
    quarter: "Q1",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Jump Shot",
    distance: "26'",
    result: "miss",
    assist: "",
  },
  {
    time: "07:40",
    quarter: "Q1",
    team: "OKC",
    player: "Jalen Williams",
    play: "Running Layup",
    distance: "7'",
    result: "miss",
    assist: "",
  },
  {
    time: "07:11",
    quarter: "Q1",
    team: "OKC",
    player: "Alex Caruso",
    play: "Driving Layup",
    distance: "2'",
    result: "made",
    assist: "Ajay Mitchell",
  },
  {
    time: "06:48",
    quarter: "Q1",
    team: "OKC",
    player: "Alex Caruso",
    play: "Running Finger Roll Layup",
    distance: "1'",
    result: "made",
    assist: "",
  },
  {
    time: "06:34",
    quarter: "Q1",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Alley Oop Layup",
    distance: "3'",
    result: "miss",
    assist: "",
  },
  {
    time: "06:27",
    quarter: "Q1",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Running Pull-Up Jump Shot",
    distance: "15'",
    result: "made",
    assist: "",
  },
  {
    time: "06:06",
    quarter: "Q1",
    team: "SAS",
    player: "Keldon Johnson",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "05:52",
    quarter: "Q1",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Fadeaway Jumper",
    distance: "13'",
    result: "miss",
    assist: "",
  },
  {
    time: "05:46",
    quarter: "Q1",
    team: "SAS",
    player: "Keldon Johnson",
    play: "Running Layup",
    distance: "2'",
    result: "miss",
    assist: "",
  },
  {
    time: "05:35",
    quarter: "Q1",
    team: "OKC",
    player: "Luguentz Dort",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "05:15",
    quarter: "Q1",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Pullup Jump Shot",
    distance: "9'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:55",
    quarter: "Q1",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "24'",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "04:42",
    quarter: "Q1",
    team: "SAS",
    player: "Keldon Johnson",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "04:26",
    quarter: "Q1",
    team: "OKC",
    player: "Luguentz Dort",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:03",
    quarter: "Q1",
    team: "OKC",
    player: "Jalen Williams",
    play: "Driving Finger Roll Layup",
    distance: "2'",
    result: "made",
    assist: "Isaiah Hartenstein",
  },
  {
    time: "03:49",
    quarter: "Q1",
    team: "SAS",
    player: "Stephon Castle",
    play: "3PT Jump Shot",
    distance: "29'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:39",
    quarter: "Q1",
    team: "OKC",
    player: "Jalen Williams",
    play: "Pullup Jump Shot",
    distance: "13'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:35",
    quarter: "Q1",
    team: "OKC",
    player: "Jalen Williams",
    play: "Driving Floating Jump Shot",
    distance: "5'",
    result: "made",
    assist: "",
  },
  {
    time: "03:11",
    quarter: "Q1",
    team: "OKC",
    player: "Jalen Williams",
    play: "Running Dunk",
    distance: "1'",
    result: "made",
    assist: "Ajay Mitchell",
  },
  {
    time: "02:50",
    quarter: "Q1",
    team: "SAS",
    player: "Dylan Harper",
    play: "3PT Step Back Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "02:43",
    quarter: "Q1",
    team: "OKC",
    player: "Jared McCain",
    play: "Running Finger Roll Layup",
    distance: "1'",
    result: "made",
    assist: "",
  },
  {
    time: "02:21",
    quarter: "Q1",
    team: "SAS",
    player: "Stephon Castle",
    play: "Driving Bank Hook Shot",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "02:13",
    quarter: "Q1",
    team: "OKC",
    player: "Jalen Williams",
    play: "Driving Layup",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "01:58",
    quarter: "Q1",
    team: "SAS",
    player: "Stephon Castle",
    play: "Driving Floating Jump Shot",
    distance: "5'",
    result: "made",
    assist: "",
  },
  {
    time: "01:48",
    quarter: "Q1",
    team: "OKC",
    player: "Jared McCain",
    play: "3PT Pullup Jump Shot",
    distance: "26'",
    result: "miss",
    assist: "",
  },
  {
    time: "01:17",
    quarter: "Q1",
    team: "OKC",
    player: "Cason Wallace",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "00:56",
    quarter: "Q1",
    team: "SAS",
    player: "Dylan Harper",
    play: "Turnaround Jump Shot",
    distance: "1'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:55",
    quarter: "Q1",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Tip Layup Shot",
    distance: "",
    result: "made",
    assist: "",
  },
  {
    time: "00:39",
    quarter: "Q1",
    team: "OKC",
    player: "Jalen Williams",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "00:16",
    quarter: "Q1",
    team: "SAS",
    player: "Dylan Harper",
    play: "Driving Layup",
    distance: "3'",
    result: "made",
    assist: "",
  },
  {
    time: "11:41",
    quarter: "Q2",
    team: "OKC",
    player: "Cason Wallace",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "11:20",
    quarter: "Q2",
    team: "SAS",
    player: "Keldon Johnson",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "11:03",
    quarter: "Q2",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "10:39",
    quarter: "Q2",
    team: "SAS",
    player: "Carter Bryant",
    play: "3PT Pullup Jump Shot",
    distance: "27'",
    result: "miss",
    assist: "",
  },
  {
    time: "10:33",
    quarter: "Q2",
    team: "OKC",
    player: "Aaron Wiggins",
    play: "3PT Running Jump Shot",
    distance: "24'",
    result: "miss",
    assist: "",
  },
  {
    time: "10:17",
    quarter: "Q2",
    team: "SAS",
    player: "Keldon Johnson",
    play: "3PT Jump Shot",
    distance: "27'",
    result: "made",
    assist: "Dylan Harper",
  },
  {
    time: "09:47",
    quarter: "Q2",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Jump Shot",
    distance: "27'",
    result: "miss",
    assist: "",
  },
  {
    time: "09:34",
    quarter: "Q2",
    team: "SAS",
    player: "Carter Bryant",
    play: "3PT Jump Shot",
    distance: "26'",
    result: "made",
    assist: "Dylan Harper",
  },
  {
    time: "09:20",
    quarter: "Q2",
    team: "OKC",
    player: "Aaron Wiggins",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "09:11",
    quarter: "Q2",
    team: "SAS",
    player: "Dylan Harper",
    play: "3PT Jump Shot",
    distance: "26'",
    result: "made",
    assist: "Victor Wembanyama",
  },
  {
    time: "08:49",
    quarter: "Q2",
    team: "OKC",
    player: "Aaron Wiggins",
    play: "3PT Pullup Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "08:23",
    quarter: "Q2",
    team: "SAS",
    player: "Dylan Harper",
    play: "Fadeaway Jumper",
    distance: "8'",
    result: "miss",
    assist: "",
  },
  {
    time: "08:10",
    quarter: "Q2",
    team: "OKC",
    player: "Cason Wallace",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "07:49",
    quarter: "Q2",
    team: "SAS",
    player: "Keldon Johnson",
    play: "Driving Layup",
    distance: "2'",
    result: "miss",
    assist: "",
  },
  {
    time: "07:48",
    quarter: "Q2",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Tip Layup Shot",
    distance: "",
    result: "made",
    assist: "",
  },
  {
    time: "07:37",
    quarter: "Q2",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "07:20",
    quarter: "Q2",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Cutting Dunk Shot",
    distance: "2'",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "07:08",
    quarter: "Q2",
    team: "OKC",
    player: "Alex Caruso",
    play: "Driving Layup",
    distance: "3'",
    result: "miss",
    assist: "",
  },
  {
    time: "06:42",
    quarter: "Q2",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "06:22",
    quarter: "Q2",
    team: "SAS",
    player: "Devin Vassell",
    play: "3PT Jump Shot",
    distance: "27'",
    result: "miss",
    assist: "",
  },
  {
    time: "06:00",
    quarter: "Q2",
    team: "SAS",
    player: "Keldon Johnson",
    play: "Driving Finger Roll Layup",
    distance: "4'",
    result: "made",
    assist: "Devin Vassell",
  },
  {
    time: "05:40",
    quarter: "Q2",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "05:07",
    quarter: "Q2",
    team: "SAS",
    player: "Luke Kornet",
    play: "Cutting Layup Shot",
    distance: "2'",
    result: "miss",
    assist: "",
  },
  {
    time: "05:02",
    quarter: "Q2",
    team: "SAS",
    player: "Harrison Barnes",
    play: "Layup",
    distance: "3'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:54",
    quarter: "Q2",
    team: "OKC",
    player: "Jared McCain",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:31",
    quarter: "Q2",
    team: "SAS",
    player: "Dylan Harper",
    play: "Driving Layup",
    distance: "4'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:16",
    quarter: "Q2",
    team: "SAS",
    player: "Devin Vassell",
    play: "Turnaround Jump Shot",
    distance: "15'",
    result: "made",
    assist: "Luke Kornet",
  },
  {
    time: "04:01",
    quarter: "Q2",
    team: "OKC",
    player: "Jalen Williams",
    play: "Driving Floating Bank Jump Shot",
    distance: "7'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:51",
    quarter: "Q2",
    team: "SAS",
    player: "Stephon Castle",
    play: "Driving Floating Jump Shot",
    distance: "6'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:47",
    quarter: "Q2",
    team: "OKC",
    player: "Jalen Williams",
    play: "Running Layup",
    distance: "2'",
    result: "made",
    assist: "Jared McCain",
  },
  {
    time: "03:30",
    quarter: "Q2",
    team: "OKC",
    player: "Jared McCain",
    play: "Running Layup",
    distance: "1'",
    result: "made",
    assist: "",
  },
  {
    time: "03:09",
    quarter: "Q2",
    team: "SAS",
    player: "Stephon Castle",
    play: "3PT Step Back Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "02:56",
    quarter: "Q2",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Step Back Jump Shot",
    distance: "18'",
    result: "miss",
    assist: "",
  },
  {
    time: "02:33",
    quarter: "Q2",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Turnaround Jump Shot",
    distance: "5'",
    result: "made",
    assist: "",
  },
  {
    time: "01:54",
    quarter: "Q2",
    team: "OKC",
    player: "Ajay Mitchell",
    play: "Pullup Jump Shot",
    distance: "9'",
    result: "miss",
    assist: "",
  },
  {
    time: "01:33",
    quarter: "Q2",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Driving Dunk",
    distance: "3'",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "01:08",
    quarter: "Q2",
    team: "OKC",
    player: "Jalen Williams",
    play: "Driving Layup",
    distance: "2'",
    result: "miss",
    assist: "",
  },
  {
    time: "01:02",
    quarter: "Q2",
    team: "OKC",
    player: "Cason Wallace",
    play: "3PT Jump Shot",
    distance: "24'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:54",
    quarter: "Q2",
    team: "SAS",
    player: "Devin Vassell",
    play: "3PT Jump Shot",
    distance: "28'",
    result: "made",
    assist: "Dylan Harper",
  },
  {
    time: "00:42",
    quarter: "Q2",
    team: "OKC",
    player: "Chet Holmgren",
    play: "3PT Jump Shot",
    distance: "",
    result: "made",
    assist: "Jalen Williams",
  },
  {
    time: "00:19",
    quarter: "Q2",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Turnaround Fadeaway Shot",
    distance: "16'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:02",
    quarter: "Q2",
    team: "OKC",
    player: "Jalen Williams",
    play: "Step Back Jump Shot",
    distance: "13'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:01",
    quarter: "Q2",
    team: "OKC",
    player: "Chet Holmgren",
    play: "Tip Layup Shot",
    distance: "2'",
    result: "miss",
    assist: "",
  },
  {
    time: "11:38",
    quarter: "Q3",
    team: "SAS",
    player: "Dylan Harper",
    play: "Running Layup",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "11:29",
    quarter: "Q3",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Fadeaway Jumper",
    distance: "13'",
    result: "miss",
    assist: "",
  },
  {
    time: "11:13",
    quarter: "Q3",
    team: "SAS",
    player: "Devin Vassell",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "11:03",
    quarter: "Q3",
    team: "SAS",
    player: "Stephon Castle",
    play: "3PT Jump Shot",
    distance: "28'",
    result: "miss",
    assist: "",
  },
  {
    time: "10:50",
    quarter: "Q3",
    team: "OKC",
    player: "Jalen Williams",
    play: "Pullup Jump Shot",
    distance: "12'",
    result: "made",
    assist: "",
  },
  {
    time: "10:32",
    quarter: "Q3",
    team: "SAS",
    player: "Devin Vassell",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "10:18",
    quarter: "Q3",
    team: "OKC",
    player: "Chet Holmgren",
    play: "3PT Jump Shot",
    distance: "26'",
    result: "made",
    assist: "Luguentz Dort",
  },
  {
    time: "10:02",
    quarter: "Q3",
    team: "SAS",
    player: "Stephon Castle",
    play: "Driving Layup",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "09:48",
    quarter: "Q3",
    team: "OKC",
    player: "Cason Wallace",
    play: "Driving Layup",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "09:31",
    quarter: "Q3",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "09:17",
    quarter: "Q3",
    team: "OKC",
    player: "Luguentz Dort",
    play: "3PT Jump Shot",
    distance: "26'",
    result: "miss",
    assist: "",
  },
  {
    time: "09:03",
    quarter: "Q3",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Step Back Jump Shot",
    distance: "15'",
    result: "miss",
    assist: "",
  },
  {
    time: "08:48",
    quarter: "Q3",
    team: "SAS",
    player: "Julian Champagnie",
    play: "Driving Layup",
    distance: "1'",
    result: "made",
    assist: "Victor Wembanyama",
  },
  {
    time: "08:20",
    quarter: "Q3",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "3PT Jump Shot",
    distance: "24'",
    result: "made",
    assist: "Jalen Williams",
  },
  {
    time: "07:55",
    quarter: "Q3",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "3PT Step Back Jump Shot",
    distance: "27'",
    result: "miss",
    assist: "",
  },
  {
    time: "07:50",
    quarter: "Q3",
    team: "OKC",
    player: "Luguentz Dort",
    play: "3PT Jump Shot",
    distance: "24'",
    result: "made",
    assist: "Jalen Williams",
  },
  {
    time: "07:18",
    quarter: "Q3",
    team: "OKC",
    player: "Chet Holmgren",
    play: "Fadeaway Jumper",
    distance: "13'",
    result: "miss",
    assist: "",
  },
  {
    time: "07:01",
    quarter: "Q3",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Jump Shot",
    distance: "26'",
    result: "made",
    assist: "Carter Bryant",
  },
  {
    time: "06:35",
    quarter: "Q3",
    team: "OKC",
    player: "Chet Holmgren",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "05:30",
    quarter: "Q3",
    team: "OKC",
    player: "Jared McCain",
    play: "3PT Jump Shot",
    distance: "",
    result: "made",
    assist: "Ajay Mitchell",
  },
  {
    time: "04:46",
    quarter: "Q3",
    team: "SAS",
    player: "Dylan Harper",
    play: "Running Layup",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "04:29",
    quarter: "Q3",
    team: "OKC",
    player: "Jalen Williams",
    play: "Driving Floating Jump Shot",
    distance: "6'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:20",
    quarter: "Q3",
    team: "SAS",
    player: "Dylan Harper",
    play: "Driving Layup",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "04:09",
    quarter: "Q3",
    team: "OKC",
    player: "Ajay Mitchell",
    play: "Pullup Jump Shot",
    distance: "16'",
    result: "made",
    assist: "",
  },
  {
    time: "03:37",
    quarter: "Q3",
    team: "OKC",
    player: "Ajay Mitchell",
    play: "Driving Reverse Layup",
    distance: "2'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:05",
    quarter: "Q3",
    team: "OKC",
    player: "Jalen Williams",
    play: "Cutting Dunk Shot",
    distance: "1'",
    result: "made",
    assist: "Isaiah Hartenstein",
  },
  {
    time: "02:35",
    quarter: "Q3",
    team: "OKC",
    player: "Jalen Williams",
    play: "Driving Hook Shot",
    distance: "3'",
    result: "miss",
    assist: "",
  },
  {
    time: "02:27",
    quarter: "Q3",
    team: "SAS",
    player: "Devin Vassell",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "02:21",
    quarter: "Q3",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Turnaround Jump Shot",
    distance: "7'",
    result: "miss",
    assist: "",
  },
  {
    time: "01:58",
    quarter: "Q3",
    team: "OKC",
    player: "Jared McCain",
    play: "Step Back Jump Shot",
    distance: "13'",
    result: "miss",
    assist: "",
  },
  {
    time: "01:57",
    quarter: "Q3",
    team: "OKC",
    player: "Jalen Williams",
    play: "Tip Layup Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "01:43",
    quarter: "Q3",
    team: "SAS",
    player: "Devin Vassell",
    play: "Pullup Jump Shot",
    distance: "12'",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "01:25",
    quarter: "Q3",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "3PT Step Back Jump Shot",
    distance: "27'",
    result: "made",
    assist: "",
  },
  {
    time: "00:47",
    quarter: "Q3",
    team: "SAS",
    player: "Dylan Harper",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:34",
    quarter: "Q3",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "00:09",
    quarter: "Q3",
    team: "SAS",
    player: "Devin Vassell",
    play: "3PT Jump Shot",
    distance: "24'",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "00:02",
    quarter: "Q3",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Pullup Jump Shot",
    distance: "27'",
    result: "miss",
    assist: "",
  },
  {
    time: "11:40",
    quarter: "Q4",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Turnaround Jump Shot",
    distance: "8'",
    result: "miss",
    assist: "",
  },
  {
    time: "11:14",
    quarter: "Q4",
    team: "SAS",
    player: "Keldon Johnson",
    play: "3PT Jump Shot",
    distance: "",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "11:02",
    quarter: "Q4",
    team: "OKC",
    player: "Ajay Mitchell",
    play: "Pullup Jump Shot",
    distance: "23'",
    result: "made",
    assist: "",
  },
  {
    time: "10:48",
    quarter: "Q4",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "3PT Jump Shot",
    distance: "28'",
    result: "miss",
    assist: "",
  },
  {
    time: "10:39",
    quarter: "Q4",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Pullup Jump Shot",
    distance: "13'",
    result: "miss",
    assist: "",
  },
  {
    time: "09:49",
    quarter: "Q4",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Driving Layup",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "09:10",
    quarter: "Q4",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Alley Oop Dunk",
    distance: "2'",
    result: "made",
    assist: "Devin Vassell",
  },
  {
    time: "08:53",
    quarter: "Q4",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "08:37",
    quarter: "Q4",
    team: "SAS",
    player: "Stephon Castle",
    play: "Fadeaway Jumper",
    distance: "6'",
    result: "miss",
    assist: "",
  },
  {
    time: "08:26",
    quarter: "Q4",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Jump Shot",
    distance: "7'",
    result: "miss",
    assist: "",
  },
  {
    time: "08:09",
    quarter: "Q4",
    team: "SAS",
    player: "Keldon Johnson",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "07:58",
    quarter: "Q4",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Running Layup",
    distance: "2'",
    result: "miss",
    assist: "",
  },
  {
    time: "07:31",
    quarter: "Q4",
    team: "SAS",
    player: "Dylan Harper",
    play: "Fadeaway Jumper",
    distance: "8'",
    result: "made",
    assist: "",
  },
  {
    time: "07:08",
    quarter: "Q4",
    team: "OKC",
    player: "Luguentz Dort",
    play: "Cutting Dunk Shot",
    distance: "2'",
    result: "made",
    assist: "Ajay Mitchell",
  },
  {
    time: "06:33",
    quarter: "Q4",
    team: "SAS",
    player: "Stephon Castle",
    play: "3PT Pullup Jump Shot",
    distance: "30'",
    result: "miss",
    assist: "",
  },
  {
    time: "06:20",
    quarter: "Q4",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "06:06",
    quarter: "Q4",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Step Back Jump Shot",
    distance: "11'",
    result: "miss",
    assist: "",
  },
  {
    time: "05:44",
    quarter: "Q4",
    team: "SAS",
    player: "Dylan Harper",
    play: "Turnaround Fadeaway Shot",
    distance: "11'",
    result: "miss",
    assist: "",
  },
  {
    time: "05:26",
    quarter: "Q4",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Driving Layup",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "05:00",
    quarter: "Q4",
    team: "SAS",
    player: "Dylan Harper",
    play: "Driving Layup",
    distance: "2'",
    result: "made",
    assist: "Victor Wembanyama",
  },
  {
    time: "04:36",
    quarter: "Q4",
    team: "SAS",
    player: "Stephon Castle",
    play: "Driving Layup",
    distance: "6'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:34",
    quarter: "Q4",
    team: "SAS",
    player: "Devin Vassell",
    play: "Jump Shot",
    distance: "17'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:19",
    quarter: "Q4",
    team: "OKC",
    player: "Jalen Williams",
    play: "Pullup Jump Shot",
    distance: "10'",
    result: "made",
    assist: "",
  },
  {
    time: "04:02",
    quarter: "Q4",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Jump Shot",
    distance: "26'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:54",
    quarter: "Q4",
    team: "SAS",
    player: "Dylan Harper",
    play: "3PT Jump Shot",
    distance: "24'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:38",
    quarter: "Q4",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Driving Dunk",
    distance: "3'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:23",
    quarter: "Q4",
    team: "OKC",
    player: "Alex Caruso",
    play: "Cutting Layup Shot",
    distance: "1'",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "03:00",
    quarter: "Q4",
    team: "SAS",
    player: "Devin Vassell",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "02:51",
    quarter: "Q4",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "3PT Running Pull-Up Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "02:25",
    quarter: "Q4",
    team: "SAS",
    player: "Devin Vassell",
    play: "3PT Jump Shot",
    distance: "",
    result: "made",
    assist: "Julian Champagnie",
  },
  {
    time: "02:10",
    quarter: "Q4",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Step Back Jump Shot",
    distance: "11'",
    result: "made",
    assist: "",
  },
  {
    time: "01:51",
    quarter: "Q4",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "26'",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "01:26",
    quarter: "Q4",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Jump Shot",
    distance: "24'",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "01:12",
    quarter: "Q4",
    team: "OKC",
    player: "Jalen Williams",
    play: "Driving Floating Jump Shot",
    distance: "11'",
    result: "made",
    assist: "Alex Caruso",
  },
  {
    time: "00:59",
    quarter: "Q4",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Running Layup",
    distance: "5'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:12",
    quarter: "Q4",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Turnaround Jump Shot",
    distance: "4'",
    result: "made",
    assist: "",
  },
  {
    time: "00:03",
    quarter: "Q4",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Driving Finger Roll Layup",
    distance: "2'",
    result: "made",
    assist: "Ajay Mitchell",
  },
  {
    time: "00:00",
    quarter: "Q4",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Floating Jump Shot",
    distance: "4'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:48",
    quarter: "OT1",
    team: "SAS",
    player: "Devin Vassell",
    play: "3PT Jump Shot",
    distance: "27'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:14",
    quarter: "OT1",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "3PT Step Back Jump Shot",
    distance: "28'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:46",
    quarter: "OT1",
    team: "SAS",
    player: "Stephon Castle",
    play: "Driving Dunk",
    distance: "1'",
    result: "made",
    assist: "",
  },
  {
    time: "03:27",
    quarter: "OT1",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Driving Floating Jump Shot",
    distance: "5'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:13",
    quarter: "OT1",
    team: "OKC",
    player: "Jalen Williams",
    play: "Running Layup",
    distance: "2'",
    result: "miss",
    assist: "",
  },
  {
    time: "02:51",
    quarter: "OT1",
    team: "SAS",
    player: "Stephon Castle",
    play: "3PT Jump Shot",
    distance: "28'",
    result: "miss",
    assist: "",
  },
  {
    time: "02:47",
    quarter: "OT1",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Putback Layup",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "02:32",
    quarter: "OT1",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "26'",
    result: "miss",
    assist: "",
  },
  {
    time: "02:21",
    quarter: "OT1",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Jump Shot",
    distance: "",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "01:52",
    quarter: "OT1",
    team: "OKC",
    player: "Jalen Williams",
    play: "Running Dunk",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "01:31",
    quarter: "OT1",
    team: "OKC",
    player: "Ajay Mitchell",
    play: "3PT Running Jump Shot",
    distance: "27'",
    result: "miss",
    assist: "",
  },
  {
    time: "01:15",
    quarter: "OT1",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "01:10",
    quarter: "OT1",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Tip Layup Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "00:58",
    quarter: "OT1",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "Driving Dunk",
    distance: "2'",
    result: "made",
    assist: "",
  },
  {
    time: "00:51",
    quarter: "OT1",
    team: "SAS",
    player: "Julian Champagnie",
    play: "3PT Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:34",
    quarter: "OT1",
    team: "OKC",
    player: "Jalen Williams",
    play: "Pullup Jump Shot",
    distance: "14'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:27",
    quarter: "OT1",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "3PT Running Jump Shot",
    distance: "28'",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "00:04",
    quarter: "OT1",
    team: "OKC",
    player: "Jalen Williams",
    play: "3PT Jump Shot",
    distance: "27'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:46",
    quarter: "OT2",
    team: "SAS",
    player: "Stephon Castle",
    play: "Driving Floating Jump Shot",
    distance: "3'",
    result: "miss",
    assist: "",
  },
  {
    time: "04:44",
    quarter: "OT2",
    team: "SAS",
    player: "Dylan Harper",
    play: "Putback Layup",
    distance: "1'",
    result: "miss",
    assist: "",
  },
  {
    time: "03:51",
    quarter: "OT2",
    team: "OKC",
    player: "Chet Holmgren",
    play: "3PT Step Back Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "03:40",
    quarter: "OT2",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Driving Dunk",
    distance: "1'",
    result: "made",
    assist: "Dylan Harper",
  },
  {
    time: "03:23",
    quarter: "OT2",
    team: "OKC",
    player: "Shai Gilgeous-Alexander",
    play: "3PT Step Back Jump Shot",
    distance: "25'",
    result: "miss",
    assist: "",
  },
  {
    time: "02:57",
    quarter: "OT2",
    team: "OKC",
    player: "Alex Caruso",
    play: "3PT Step Back Jump Shot",
    distance: "",
    result: "miss",
    assist: "",
  },
  {
    time: "02:34",
    quarter: "OT2",
    team: "SAS",
    player: "Dylan Harper",
    play: "3PT Pullup Jump Shot",
    distance: "31'",
    result: "miss",
    assist: "",
  },
  {
    time: "02:24",
    quarter: "OT2",
    team: "OKC",
    player: "Cason Wallace",
    play: "3PT Jump Shot",
    distance: "27'",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "02:04",
    quarter: "OT2",
    team: "SAS",
    player: "Dylan Harper",
    play: "Driving Finger Roll Layup",
    distance: "1'",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "01:30",
    quarter: "OT2",
    team: "SAS",
    player: "Dylan Harper",
    play: "Driving Layup",
    distance: "3'",
    result: "miss",
    assist: "",
  },
  {
    time: "01:21",
    quarter: "OT2",
    team: "OKC",
    player: "Jalen Williams",
    play: "3PT Jump Shot",
    distance: "28'",
    result: "made",
    assist: "Shai Gilgeous-Alexander",
  },
  {
    time: "01:01",
    quarter: "OT2",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Dunk",
    distance: "",
    result: "made",
    assist: "Dylan Harper",
  },
  {
    time: "00:46",
    quarter: "OT2",
    team: "OKC",
    player: "Alex Caruso",
    play: "Driving Reverse Layup",
    distance: "1'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:44",
    quarter: "OT2",
    team: "OKC",
    player: "Chet Holmgren",
    play: "Putback Layup",
    distance: "2'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:40",
    quarter: "OT2",
    team: "OKC",
    player: "Jalen Williams",
    play: "Putback Layup",
    distance: "3'",
    result: "miss",
    assist: "",
  },
  {
    time: "00:22",
    quarter: "OT2",
    team: "SAS",
    player: "Victor Wembanyama",
    play: "Alley Oop Dunk",
    distance: "2'",
    result: "made",
    assist: "Stephon Castle",
  },
  {
    time: "00:18",
    quarter: "OT2",
    team: "OKC",
    player: "Jalen Williams",
    play: "Driving Finger Roll Layup",
    distance: "1'",
    result: "miss",
    assist: "",
  },
];
