export const knicksPlayers = [
  {
    name: "Jalen Brunson",
    position: "Guard",
    number: 11,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629029.png",
  },
  {
    name: "Karl-Anthony Towns",
    position: "Center",
    number: 32,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631114.png",
  },
  {
    name: "OG Anunoby",
    position: "Foward",
    number: 8,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631096.png",
  },
  {
    name: "Mikal Bridges",
    position: "Guard",
    number: 25,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629652.png",
  },
  {
    name: "Josh Hart",
    position: "Forward",
    number: 3,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628392.png",
  },
  {
    name: "Landry Shamet",
    position: "Guard",
    number: 44,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1627936.png",
  },
  {
    name: "Miles McBride",
    position: "Guard",
    number: 2,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642272.png",
  },
  {
    name: "Jose Alvarado",
    position: "Guard",
    number: 5,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631119.png",
  },
  {
    name: "Mitchell Robinson",
    position: "Center",
    number: 23,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1641717.png",
  },
  {
    name: "Jordan Clarkson",
    position: "Guard",
    number: 0,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630598.png",
  },
  {
    name: "Pacôme Dadiet",
    position: "Forward",
    number: 4,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642869.png",
  },
  {
    name: "Mohamed Diawara",
    position: "Forward",
    number: 51,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642870.png",
  },
  {
    name: "Ariel Hukporti",
    position: "Center",
    number: 55,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642871.png",
  },
  {
    name: "Tyler Kolek",
    position: "Guard",
    number: 13,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642872.png",
  },
  {
    name: "Jeremy Sochan",
    position: "Forward",
    number: 20,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631095.png",
  },
];

export const spursPlayers = [
  {
    name: "Victor Wembanyama",
    position: "Center",
    number: 1,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1641705.png",
  },
  {
    name: "Dylan Harper",
    position: "Guard",
    number: 2,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642844.png",
  },
  {
    name: "De'Aaron Fox",
    position: "Guard",
    number: 4,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628368.png",
  },
  {
    name: "Stephon Castle",
    position: "Guard",
    number: 5,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642264.png",
  },
  {
    name: "Julian Champagnie",
    position: "Forward",
    number: 30,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630577.png",
  },
  {
    name: "Devin Vassell",
    position: "Forward",
    number: 24,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630170.png",
  },
  {
    name: "Keldon Johnson",
    position: "Guard/Forward",
    number: 3,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629640.png",
  },
  {
    name: "Carter Bryant",
    position: "Forward",
    number: 11,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642868.png",
  },
  {
    name: "Harrison Barnes",
    position: "Forward",
    number: 40,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203084.png",
  },
  {
    name: "Luke Kornet",
    position: "Center",
    number: 7,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628436.png",
  },
  {
    name: "Bismack Biyombo",
    position: "Center",
    number: 18,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/202687.png",
  },
  {
    name: "Mason Plumlee",
    position: "Forward",
    number: 45,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203486.png",
  },
  {
    name: "Kelly Olynyk",
    position: "Center",
    number: 8,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203482.png",
  },
  {
    name: "Lindy Waters III",
    position: "Guard",
    number: 43,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630322.png",
  },
  {
    name: "Jordan McLaughlin",
    position: "Guard",
    number: 0,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629162.png",
  },
];

export const cavaliersPlayers = [
  {
    name: "Donovan Mitchell",
    position: "Guard",
    number: 45,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628378.png",
  },
  {
    name: "James Harden",
    position: "Guard",
    number: 13,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/201935.png",
  },
  {
    name: "Evan Mobley",
    position: "Forward",
    number: 4,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630172.png",
  },
  {
    name: "Jarrett Allen",
    position: "Center",
    number: 31,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628385.png",
  },
  {
    name: "Dean Wade",
    position: "Forward",
    number: 32,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629137.png",
  },
  {
    name: "Max Strus",
    position: "Forward",
    number: 2,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629136.png",
  },
  {
    name: "Dennis Schröder",
    position: "Guard",
    number: 8,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203471.png",
  },
  {
    name: "Sam Merrill",
    position: "Guard",
    number: 5,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629138.png",
  },
  {
    name: "Keon Ellis",
    position: "Guard",
    number: 14,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642867.png",
  },
  {
    name: "Thomas Bryant",
    position: "Center",
    number: 3,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628384.png",
  },
  {
    name: "Larry Nance Jr.",
    position: "Forward",
    number: 22,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203487.png",
  },
  {
    name: "Craig Porter Jr.",
    position: "Guard",
    number: 9,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642866.png",
  },
  {
    name: "Tyrese Proctor",
    position: "Guard",
    number: 24,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642865.png",
  },
  {
    name: "Nae'Qwan Tomlinson",
    position: "Forward",
    number: 35,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642864.png",
  },
  {
    name: "Jaylon Tyson",
    position: "Guard",
    number: 20,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642863.png",
  },
];

export const sixersPlayers = [
  {
    name: "Joel Embiid",
    position: "Center",
    number: 21,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203954.png",
  },
  {
    name: "Tyrese Maxey",
    position: "Guard",
    number: 0,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629650.png",
  },
  {
    name: "Paul George",
    position: "Forward",
    number: 8,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203953.png",
  },
  {
    name: "VJ Edgecombe",
    position: "Guard",
    number: 77,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642862.png",
  },
  {
    name: "Kelly Oubre Jr.",
    position: "Forward",
    number: 9,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203484.png",
  },
  {
    name: "Andre Drummond",
    position: "Center",
    number: 1,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203079.png",
  },
  {
    name: "Quentin Grimes",
    position: "Guard",
    number: 5,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631100.png",
  },
  {
    name: "Justin Edwards",
    position: "Forward",
    number: 11,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642861.png",
  },
  {
    name: "Dominick Barlow",
    position: "Forward",
    number: 25,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642860.png",
  },
  {
    name: "Adem Bona",
    position: "Forward",
    number: 30,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642859.png",
  },
  {
    name: "Dalen Terry",
    position: "Forward",
    number: 14,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642858.png",
  },
  {
    name: "Trendon Watford",
    position: "Guard",
    number: 12,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642857.png",
  },
  {
    name: "Jabari Walker",
    position: "Forward",
    number: 33,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642856.png",
  },
  {
    name: "Johni Broome",
    position: "Forward",
    number: 22,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642855.png",
  },
  {
    name: "Kyle Lowry",
    position: "Guard",
    number: 7,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/200768.png",
  },
];

export const hawksPlayers = [
  {
    name: "Jalen Johnson",
    position: "Forward",
    number: 1,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642868.png",
  },
  {
    name: "CJ McCollum",
    position: "Guard",
    number: 3,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203468.png",
  },
  {
    name: "Dyson Daniels",
    position: "Guard",
    number: 5,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642867.png",
  },
  {
    name: "Onyeka Okongwu",
    position: "Center",
    number: 17,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630171.png",
  },
  {
    name: "Nickeil Alexander-Walker",
    position: "Guard",
    number: 7,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630172.png",
  },
  {
    name: "Jonathan Kuminga",
    position: "Forward",
    number: 0,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631097.png",
  },
  {
    name: "Gabe Vincent",
    position: "Guard",
    number: 4,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628377.png",
  },
  {
    name: "Mouhamed Gueye",
    position: "Forward",
    number: 18,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642869.png",
  },
  {
    name: "Buddy Hield",
    position: "Guard",
    number: 8,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/202335.png",
  },
  {
    name: "Corey Kispert",
    position: "Forward",
    number: 24,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631098.png",
  },
  {
    name: "Zaccharie Risacher",
    position: "Forward",
    number: 10,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642870.png",
  },
  {
    name: "Keaton Wallace",
    position: "Guard",
    number: 2,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642871.png",
  },
  {
    name: "Tony Bradley",
    position: "Center",
    number: 13,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203115.png",
  },
  {
    name: "Asa Newell",
    position: "Forward",
    number: 14,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642872.png",
  },
];
