export const spursPlayers = [
  {
    name: "Victor Wembanyama",
    position: "Center",
    number: 1,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1641705.png",
  },
  {
    name: "Dylan Harper",
    position: "Guard",
    number: 2,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642844.png",
  },
  {
    name: "De'Aaron Fox",
    position: "Guard",
    number: 4,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628368.png",
  },
  {
    name: "Stephon Castle",
    position: "Guard",
    number: 5,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642264.png",
  },
  {
    name: "Julian Champagnie",
    position: "Forward",
    number: 30,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630577.png",
  },
  {
    name: "Devin Vassell",
    position: "Forward",
    number: 24,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630170.png",
  },
  {
    name: "Keldon Johnson",
    position: "Guard/Forward",
    number: 3,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629640.png",
  },
  {
    name: "Carter Bryant",
    position: "Forward",
    number: 11,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642868.png",
  },
  {
    name: "Harrison Barnes",
    position: "Forward",
    number: 40,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203084.png",
  },
  {
    name: "Luke Kornet",
    position: "Center",
    number: 7,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628436.png",
  },
  {
    name: "Bismack Biyombo",
    position: "Center",
    number: 18,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/202687.png",
  },
  {
    name: "Mason Plumlee",
    position: "Forward",
    number: 45,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203486.png",
  },
  {
    name: "Kelly Olynyk",
    position: "Center",
    number: 8,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203482.png",
  },
  {
    name: "Lindy Waters III",
    position: "Guard",
    number: 43,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630322.png",
  },
  {
    name: "Jordan McLaughlin",
    position: "Guard",
    number: 0,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629162.png",
  },
];

export const knicksPlayers = [
  {
    name: "Jalen Brunson",
    position: "Guard",
    number: 11,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629029.png",
  },
  {
    name: "Karl-Anthony Towns",
    position: "Center",
    number: 32,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631114.png",
  },
  {
    name: "OG Anunoby",
    position: "Foward",
    number: 8,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631096.png",
  },
  {
    name: "Mikal Bridges",
    position: "Guard",
    number: 25,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629652.png",
  },
  {
    name: "Josh Hart",
    position: "Forward",
    number: 3,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628392.png",
  },
  {
    name: "Landry Shamet",
    position: "Guard",
    number: 44,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1627936.png",
  },
  {
    name: "Miles McBride",
    position: "Guard",
    number: 2,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642272.png",
  },
  {
    name: "Jose Alvarado",
    position: "Guard",
    number: 5,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631119.png",
  },
  {
    name: "Mitchell Robinson",
    position: "Center",
    number: 23,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1641717.png",
  },
  {
    name: "Ajay Mitchell",
    position: "Guard",
    number: 25,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642349.png",
  },
  {
    name: "Jordan Clarkson",
    position: "Guard",
    number: 0,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630598.png",
  },
];
