export const knicksPlayers = [
  {
    name: "Jalen Brunson",
    position: "Guard",
    number: 11,
    imageUrl: "/players/nyk/brunson.png",
  },
  {
    name: "Karl-Anthony Towns",
    position: "Center",
    number: 32,
    imageUrl: "/players/nyk/kat.png",
  },
  {
    name: "OG Anunoby",
    position: "Foward",
    number: 8,
    imageUrl: "/players/nyk/og.png",
  },
  {
    name: "Mikal Bridges",
    position: "Guard",
    number: 25,
    imageUrl: "/players/nyk/bridges.png",
  },
  {
    name: "Josh Hart",
    position: "Forward",
    number: 3,
    imageUrl: "/players/nyk/hart.png",
  },
  {
    name: "Landry Shamet",
    position: "Guard",
    number: 44,
    imageUrl: "/players/nyk/shamet.png",
  },
  {
    name: "Miles McBride",
    position: "Guard",
    number: 2,
    imageUrl: "/players/nyk/mcbride.png",
  },
  {
    name: "Jose Alvarado",
    position: "Guard",
    number: 5,
    imageUrl: "/players/nyk/alvarado.png",
  },
  {
    name: "Mitchell Robinson",
    position: "Center",
    number: 23,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1641717.png",
  },
  {
    name: "Jordan Clarkson",
    position: "Guard",
    number: 0,
    imageUrl: "/players/nyk/clarkson.png",
  },
  {
    name: "Pacôme Dadiet",
    position: "Forward",
    number: 4,
    imageUrl: "/players/nyk/dadiet.png",
  },
  {
    name: "Mohamed Diawara",
    position: "Forward",
    number: 51,
    imageUrl: "/players/nyk/diawara.png",
  },
  {
    name: "Ariel Hukporti",
    position: "Center",
    number: 55,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642871.png",
  },
  {
    name: "Tyler Kolek",
    position: "Guard",
    number: 13,
    imageUrl: "/players/nyk/kolek.png",
  },
  {
    name: "Jeremy Sochan",
    position: "Forward",
    number: 20,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631095.png",
  },
];

export const spursPlayers = [
  {
    name: "Victor Wembanyama",
    position: "Center",
    number: 1,
    imageUrl: "/players/sas/wemby.png",
  },
  {
    name: "Dylan Harper",
    position: "Guard",
    number: 2,
    imageUrl: "/players/sas/harper.png",
  },
  {
    name: "De'Aaron Fox",
    position: "Guard",
    number: 4,
    imageUrl: "/players/sas/fox.png",
  },
  {
    name: "Stephon Castle",
    position: "Guard",
    number: 5,
    imageUrl: "/players/sas/castle.png",
  },
  {
    name: "Julian Champagnie",
    position: "Forward",
    number: 30,
    imageUrl: "/players/sas/champagnie.png",
  },
  {
    name: "Devin Vassell",
    position: "Forward",
    number: 24,
    imageUrl: "/players/sas/vassell.png",
  },
  {
    name: "Keldon Johnson",
    position: "Guard/Forward",
    number: 3,
    imageUrl: "/players/sas/johnson.png",
  },
  {
    name: "Carter Bryant",
    position: "Forward",
    number: 11,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642868.png",
  },
  {
    name: "Harrison Barnes",
    position: "Forward",
    number: 40,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203084.png",
  },
  {
    name: "Luke Kornet",
    position: "Center",
    number: 7,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1628436.png",
  },
  {
    name: "Bismack Biyombo",
    position: "Center",
    number: 18,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/202687.png",
  },
  {
    name: "Mason Plumlee",
    position: "Forward",
    number: 45,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203486.png",
  },
  {
    name: "Kelly Olynyk",
    position: "Center",
    number: 8,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203482.png",
  },
  {
    name: "Lindy Waters III",
    position: "Guard",
    number: 43,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1630322.png",
  },
  {
    name: "Jordan McLaughlin",
    position: "Guard",
    number: 0,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1629162.png",
  },
];

export const cavaliersPlayers = [
  {
    name: "Donovan Mitchell",
    position: "Guard",
    number: 45,
    imageUrl: "/players/cle/spida.png",
  },
  {
    name: "James Harden",
    position: "Guard",
    number: 13,
    imageUrl: "/players/cle/harden.png",
  },
  {
    name: "Evan Mobley",
    position: "Forward",
    number: 4,
    imageUrl: "/players/cle/mobley.png",
  },
  {
    name: "Jarrett Allen",
    position: "Center",
    number: 31,
    imageUrl: "/players/cle/allen.png",
  },
  {
    name: "Dean Wade",
    position: "Forward",
    number: 32,
    imageUrl: "/players/cle/wade.png",
  },
  {
    name: "Max Strus",
    position: "Forward",
    number: 2,
    imageUrl: "/players/cle/strus.png",
  },
  {
    name: "Dennis Schröder",
    position: "Guard",
    number: 8,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203471.png",
  },
  {
    name: "Sam Merrill",
    position: "Guard",
    number: 5,
    imageUrl: "/players/cle/merrill.png",
  },
  {
    name: "Keon Ellis",
    position: "Guard",
    number: 14,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642867.png",
  },
  {
    name: "Thomas Bryant",
    position: "Center",
    number: 3,
    imageUrl: "/players/cle/bryant.png",
  },
  {
    name: "Larry Nance Jr.",
    position: "Forward",
    number: 22,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203487.png",
  },
  {
    name: "Craig Porter Jr.",
    position: "Guard",
    number: 9,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642866.png",
  },
  {
    name: "Tyrese Proctor",
    position: "Guard",
    number: 24,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642865.png",
  },
  {
    name: "Nae'Qwan Tomlinson",
    position: "Forward",
    number: 35,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642864.png",
  },
  {
    name: "Jaylon Tyson",
    position: "Guard",
    number: 20,
    imageUrl: "/players/cle/tyson.png",
  },
];

export const sixersPlayers = [
  {
    name: "Joel Embiid",
    position: "Center",
    number: 21,
    imageUrl: "/players/phi/embiid.png",
  },
  {
    name: "Tyrese Maxey",
    position: "Guard",
    number: 0,
    imageUrl: "/players/phi/maxey.png",
  },
  {
    name: "Paul George",
    position: "Forward",
    number: 8,
    imageUrl: "/players/phi/pg.png",
  },
  {
    name: "VJ Edgecombe",
    position: "Guard",
    number: 77,
    imageUrl: "/players/phi/vj.png",
  },
  {
    name: "Kelly Oubre Jr.",
    position: "Forward",
    number: 9,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203484.png",
  },
  {
    name: "Andre Drummond",
    position: "Center",
    number: 1,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/203079.png",
  },
  {
    name: "Quentin Grimes",
    position: "Guard",
    number: 5,
    imageUrl: "/players/phi/grimes.png",
  },
  {
    name: "Justin Edwards",
    position: "Forward",
    number: 11,
    imageUrl: "/players/phi/edwards.png",
  },
  {
    name: "Dominick Barlow",
    position: "Forward",
    number: 25,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642860.png",
  },
  {
    name: "Adem Bona",
    position: "Forward",
    number: 30,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642859.png",
  },
  {
    name: "Dalen Terry",
    position: "Forward",
    number: 14,
    imageUrl: "/players/phi/terry.png",
  },
  {
    name: "Trendon Watford",
    position: "Guard",
    number: 12,
    imageUrl: "/players/phi/watford.png",
  },
  {
    name: "Jabari Walker",
    position: "Forward",
    number: 33,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642856.png",
  },
  {
    name: "Johni Broome",
    position: "Forward",
    number: 22,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642855.png",
  },
  {
    name: "Kyle Lowry",
    position: "Guard",
    number: 7,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/200768.png",
  },
];

export const hawksPlayers = [
  {
    name: "Jalen Johnson",
    position: "Forward",
    number: 1,
    imageUrl: "/players/atl/johnson.png",
  },
  {
    name: "CJ McCollum",
    position: "Guard",
    number: 3,
    imageUrl: "/players/atl/cj.png",
  },
  {
    name: "Dyson Daniels",
    position: "Guard",
    number: 5,
    imageUrl: "/players/atl/daniels.png",
  },
  {
    name: "Onyeka Okongwu",
    position: "Center",
    number: 17,
    imageUrl: "/players/atl/okongwu.png",
  },
  {
    name: "Nickeil Alexander-Walker",
    position: "Guard",
    number: 7,
    imageUrl: "/players/atl/walker.png",
  },
  {
    name: "Jonathan Kuminga",
    position: "Forward",
    number: 0,
    imageUrl: "/players/atl/kuminga.png",
  },
  {
    name: "Gabe Vincent",
    position: "Guard",
    number: 4,
    imageUrl: "/players/atl/vincent.png",
  },
  {
    name: "Mouhamed Gueye",
    position: "Forward",
    number: 18,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642869.png",
  },
  {
    name: "Buddy Hield",
    position: "Guard",
    number: 8,
    imageUrl: "/players/atl/hield.png",
  },
  {
    name: "Corey Kispert",
    position: "Forward",
    number: 24,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1631098.png",
  },
  {
    name: "Zaccharie Risacher",
    position: "Forward",
    number: 10,
    imageUrl: "/players/atl/risacher.png",
  },
  {
    name: "Keaton Wallace",
    position: "Guard",
    number: 2,
    imageUrl: "/players/atl/wallace.png",
  },
  {
    name: "Tony Bradley",
    position: "Center",
    number: 13,
    imageUrl: "/players/atl/bradley.png",
  },
  {
    name: "Asa Newell",
    position: "Forward",
    number: 14,
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/260x190/1642872.png",
  },
];
